version: '2.1'
orbs:
  node: circleci/node@5.0.3
  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      # - node/install:
      #     install-yarn: true
      #     node-version: '16.13'
      # - run: node --version
      # - run: npm --version
workflows:
    example-workflow:
      jobs:
        - aws-ecr/build-and-push-image:
            repo: new 
            tag: latest,v0.${CIRCLE_BUILD_NUM} 
            path: .




# workflows:
#   test_my_app:
#     jobs:
#       - install-node-example
