# This is a basic workflow to help you get started whhith Actionsg

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

 
jobs: 
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          pwd
          ls
