# This is a basic workflow to help you get started whhith Actionsgee

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

 
jobs: 
  build:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          pm2 restart index.js
          pwd
          ls
          ssh -t ubuntu@44.203.176.30 "rsync -zhvr -e . ubuntu@44.203.176.30:/home/ubuntu/test/"